"""initial schema

Revision ID: b7390c21f9ae
Revises: 
Create Date: 2026-04-04 23:26:39.178018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7390c21f9ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boss_account_id', sa.String(length=128), nullable=False, comment='Boss 直聘账号 ID'),
    sa.Column('job_id', sa.String(length=128), nullable=False, comment='Boss 直聘岗位 ID'),
    sa.Column('job_name', sa.String(length=128), nullable=True, comment='岗位名称'),
    sa.Column('job_type', sa.String(length=64), nullable=True, comment='岗位类型'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='active/disabled'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boss_account_id', 'job_id', name='uq_boss_account_job')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encrypt_geek_id', sa.String(length=128), nullable=False, comment='Boss 直聘候选人唯一标识'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='/wapi/ 接口原始 JSON'),
    sa.Column('detail_url', sa.String(length=512), nullable=True, comment='详情页 URL 路径'),
    sa.Column('boss_account_id', sa.String(length=128), nullable=True, comment='来源 Boss 账号 ID'),
    sa.Column('job_id', sa.String(length=128), nullable=True, comment='关联岗位 jobId'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encrypt_geek_id')
    )
    op.create_table('store_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wechat_userid', sa.String(length=128), nullable=False, comment='企业微信 userid'),
    sa.Column('store_id', sa.String(length=64), nullable=False, comment='门店 ID'),
    sa.Column('store_name', sa.String(length=128), nullable=True, comment='门店名称'),
    sa.Column('boss_account_id', sa.String(length=128), nullable=False, comment='Boss 直聘账号 ID'),
    sa.Column('storage_state_path', sa.String(length=512), nullable=False, comment='storageState 文件路径'),
    sa.Column('job_type', sa.String(length=64), nullable=True, comment='岗位类型'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='active/disabled'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wechat_userid')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('op_type', sa.String(length=32), nullable=False, comment='screening/greeting/summary'),
    sa.Column('boss_account_id', sa.String(length=128), nullable=True, comment='Boss 账号 ID'),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False, comment='success/failed/quota_exceeded'),
    sa.Column('quota_consumed', sa.Integer(), server_default='0', nullable=False, comment='本次消耗配额数'),
    sa.Column('detail', sa.JSON(), nullable=True, comment='操作详情'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('hard_rule_results', sa.JSON(), nullable=True, comment='硬规则逐项判断结果'),
    sa.Column('llm_raw_output', sa.JSON(), nullable=True, comment='LLM 原始输出'),
    sa.Column('job_profile_version', sa.String(length=64), nullable=True, comment='岗位画像配置版本'),
    sa.Column('final_verdict', sa.String(length=32), nullable=False, comment='推荐沟通/可以看看/不建议'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoring_snapshots')
    op.drop_table('operation_logs')
    op.drop_table('store_accounts')
    op.drop_table('candidates')
    op.drop_table('boss_jobs')
    # ### end Alembic commands ###
